### PR TITLE
Fix Nested Type Generate

### PR DESCRIPTION
**Pull request by lifeengines**
sometimes we wan't keep the nested types even it's compiler generated,
this patch made there names works for c#.e.g:
made output like:
```
	private sealed class __c__DisplayClass20_0 // TypeDefIndex: 7165
	{
		// Fields
		public CharacterItem script; // 0x10

		// Constructors
		public __c__DisplayClass20_0() {} // 0x00B0B320-0x00B0B328

		// Methods
		internal bool _UpdateInFormation_b__1(DungeonData.CombatHero e) => default; // 0x00B0B634-0x00B0B680
	}
```
instead of:
```
	private sealed class <>c__DisplayClass20_0 // TypeDefIndex: 7165
	{
		// Fields
		public CharacterItem script; // 0x10

		// Constructors
		public <>c__DisplayClass20_0() {} // 0x00B0B320-0x00B0B328

		// Methods
		internal bool <UpdateInFormation>b__1(DungeonData.CombatHero e) => default; // 0x00B0B634-0x00B0B680
	}
```

### CODE REVIEW

**Comment by djkaty** [comment]
Hey! Thanks for the PR.

The change to `MethodBase` is fine since it only modifies `CSharpName`, but you cannot change the meaning of `BaseName` (and consequently `Name` etc.) in `TypeInfo` as it must be the CTS-style type name in the binary. Instead, modify `TypeInfo.CSharpName` and leave the rest intact. See https://katyscode.wordpress.com/2020/08/10/practical-il2cpp-protobuf/#highlighter_485124:~:text=Tip%3A%20There%20are%20quite%20a%20few,the%20local%20scope%20specified%20in%20usingScope. for more details on what the various name properties mean.

For `FieldInfo`, please modify `MemberInfo.CSharpSafeName` instead of adding a new override. This will also eliminate the need for #69 😎

**Comment by lifeengines** [comment]
okay I get it.maybe it's only need replace name in unmangleName(string name),I made some test,it's works well,is that okay?
TypeInfo.cs->
```
        private static string unmangleName(string name) {
            var index = name.IndexOf("`", StringComparison.Ordinal);
            if (index != -1)
                name = name.Remove(index);
            name = name.Replace("<", "_").Replace(">", "_");
            return name;
        }
```
MemberInfo.cs->
```
        public string CSharpSafeName => (Constants.Keywords.Contains(Name) ? "@" + Name : Name).Replace("<", "_").Replace(">", "_");
```

**Comment by djkaty** [comment]
Yes, I just looked at the code and I think this works well. We should probably also change the `MethodBase` method ending in ': Name.Replace...` to just use `: CSharpSafeName`?

**Comment by lifeengines** [comment]
right,use a CSharpSafeName property it rather good than change CSharpName,I will try and make a new pull request

**Comment by djkaty** [comment]
No, I meant just use the one from `MemberInfo` 👍

**Comment by lifeengines** [comment]
just change  : Name.Replace("<","_").Replace(">","_"); to  : CSharpSafeName?

**Comment by djkaty** [comment]
Yes, but I guess that will ruin any generic parameters like you said.

**Comment by lifeengines** [comment]
maybe it's not an big problem,compiler generated member name won't intact with interface I guess.

**Comment by djkaty** [comment]
That's true but CSharpSafeName will be called for ALL types when the C# code is generated....

**Comment by lifeengines** [comment]
right,I feel use a new property maybe good,since change the CSharpName may ruin the recursive call,like:
```
                var implementingInterface = DeclaringType.ImplementedInterfaces.FirstOrDefault(i => Name.StartsWith(i.Namespace + "." + i.CSharpName + "."))
                    ?? DeclaringType.ImplementedInterfaces.FirstOrDefault(i => Name.StartsWith(i.Namespace + "." + i.GetCSharpTypeDeclarationName().Replace(" ", "") + "."));
````
and I checked the code,there are only few place in c# generate code should be change

**Comment by djkaty** [comment]
Okay, I'll just let you make a new PR with what you think is best. The main things to bear in mind are:

1. None of the name properties or methods outputs should be changed EXCEPT for those outputting C# code, ie. CSharpName, CSharpSafeName etc. (all the ones with CSharp in the name) - none of the others should be changed. BaseName, UnmangledBaseName, Name, FullName etc. should all be left alone

2. Minimize the number of places where you are substituting < and >. Preferably only in one place and have all the other locations call it. If we need to make further name modifications in the future, that will make the code more maintainable.

**Comment by lifeengines** [comment]
I made a new PR,this could be closed.Also I only do the test on one project,it's works.

**Pull request closed without merging**
