### PR TITLE
Automatic generation of IDA script

### PR DESCRIPTION
**Pull request by StijnSimons**
Unfinished: just reserving this here.

### CODE REVIEW

**Comment by djkaty** [comment]
No problem, let me know when you're ready for me to take a look.

Note that I would prefer you make a separate class for it (Il2CppIDAScriptDumper or something), I was planning today to move the initialization of Il2CppReflector out of Il2CppDumper's constructor and take it as a constructor argument instead so that the model (the contents of Il2CppReflector) could be used in other objects without having to rebuild it, and that Il2CppDumper would purely return text. I didn't get round to it though.

**Comment by djkaty** [comment]
Okay I've pushed all the changes that will affect you, fire away :)

**Comment by StijnSimons** [comment]
Unfortunately i'm quite busy with school work currently so i will be delaying this quite a bit.

**Comment by djkaty** [comment]
Closing, this work is moved over to #13

**Pull request closed without merging**
