### PR TITLE
Progress with IDA Script generation

### PR DESCRIPTION
**Pull request by carterbush**
Hey! I've been trying to pull apart something and I've found your work really helpful! To that end, I've had a go at the script generation. 

I only have a vague idea what I'm doing, but it seems to be doing what I want it to do, so I figured I'd share what I have so far. 

Most of it is based on the original Prefare/Il2CppDumper

### CODE REVIEW

**Comment by djkaty** [comment]
That looks pretty awesome! I'll have to get into it properly after I return from Christmas break but it looks good. There are two kinds of string literals used in il2cpp and I currently only read in one of the sets, perhaps the index out of bounds exception is because of that? Check out the other string literal pointer in Il2CppGlobalMetadataHeader!

**Comment by djkaty** [comment]
Okay I've skimmed over this, I really appreciate that you went back and changed the coding style to match :) A few small comments and then we can get this merged:

1. Replace all instances of `toHex` with the provided extension method `long.ToAddressString()` (see Extensions.cs)
2. Replace the pre-amble texts with a multi-line string, you can do it like this:

`@"line1
line2
line3
....
";`

3. Let's just remove all the commented out string literal stuff and put in a `// TODO: String literals`, I'm not a big fan of committing commented out code. We can take a look at this after the merge.

4. Comment declaration and initialization of MetadataUsages in Il2CppBinary.cs

5. if statement bracketing style in Metadata.cs line 123

6. Logic that applies to analysing/reverse engineering the files should be separated from output/presentation logic. Therefore I think the logic for BuildMetadataUsages should be moved to the constructor of Metadata (or a function called from it), plus a property in Metadata (and a surrogate property in Il2CppInspector) to retrieve the list, similar to how eg. Metadata.Strings is set up. Therefore DecodeEncodedSourceIndex should also be moved to Metadata. The reason for this is in case any future output class wants to access this data too. As much as possible, the output classes should only need to access the model, not any lower level objects (the package, metadata or binary).

7. Lowercase the first character (camelCase) the first character of all private methods in the script dumper class.

8. Move MetadataUsageType and MetadataUsage should be moved to the Il2CppInspector.cs file (I think?) at the end.

9. For consistency, replace
`           foreach (var method in methods) {
                if (!method.VirtualAddress.HasValue) continue;`

with
`foreach (var method in methods.Where(m => m.VirtualAddress.HasValue)) ....`

10. The non-output logic in writeUsages looks like it should probably go in the MetadataUsage class itself. Not really sure whether each possible usage type should have its own derived class, a generic self-implementation or just a bunch of fields which are valid or not depending on the MetadataUsageType. They all work, you can decide.

I haven't actually looked at the Python script or output itself yet. I like your code a lot overall and appreciate the effort to make it blend in, just needs small refactoring :) I promise next time I'll be a proper human being and use inline review comments, sorry I had no idea this was gonna be so long :P

**Comment by carterbush** [comment]
No problems, thanks for the feedback! Apologies I've been quiet on this - I've gone back to work after the Christmas break, so I'm a bit short on time, but I'll take another pass hopefully this weekend :)

**Comment by djkaty** [comment]
Reviewed your changes. Looks pretty great! Are there any more commits to come?

**Comment by djkaty** [comment]
The metadata usage outputs of generics have <...> added afterwards (examples below). Is it meant to be like that? I'm not familiar with the low-level naming conventions.

```
SetName(0x00000001038B8370, 'Method$PlatformDependentValue`1[T]<T>..ctor')
SetName(0x00000001038B8378, 'Method$PlatformDependentValue`1[T]<T>.set_Phone')
SetName(0x00000001038B8380, 'Method$PlatformDependentValue`1[T]<T>.set_Tablet')
SetName(0x00000001038B8388, 'Method$PlatformDependentValue`1[T]<T>.set_PC')
SetName(0x00000001038A71C8, 'Class$List`1[HeroPickerButton]')
SetName(0x00000001038A71D0, 'Class$List`1[AbsDeckPickerTrayDisplay+DeckTrayLoaded]')
SetName(0x00000001038B8240, 'Method$List`1[T]<T>..ctor')
SetName(0x00000001038B8248, 'Method$List`1[T]<T>..ctor')
SetName(0x00000001038B8250, 'Method$List`1[T]<T>.Add')
SetName(0x00000001038A71D8, 'Class$Navigation')
SetName(0x00000001038A3AF0, 'Class$Object')
SetName(0x00000001038B82D0, 'Method$List`1[T]<T>.ToArray')
SetName(0x00000001038A4910, 'Class$List`1[UnityEngine.Transform]')
SetName(0x00000001038B8338, 'Method$List`1[T]<T>..ctor')
SetName(0x00000001038B8340, 'Method$List`1[T]<T>.GetEnumerator')
SetName(0x00000001038B8348, 'Method$List`1[T]+Enumerator[T]<T>.get_Current')
SetName(0x00000001038B8350, 'Method$List`1[T]<T>.Contains')
SetName(0x00000001038B8358, 'Method$List`1[T]<T>.Add')
SetName(0x00000001038B8360, 'Method$List`1[T]+Enumerator[T]<T>.MoveNext')
SetName(0x00000001038B8368, 'Method$List`1[T]+Enumerator[T]<T>.Dispose')
```

**Comment by carterbush** [comment]
Hm I'll be honest, I'm not sure myself!

**Comment by djkaty** [comment]
I looked at some other binaries and the naming conventions differ depending on the target platform, so I don't think there is any right or wrong way there, but none of them included the generic parameters twice.

If you could modify the code so that it doesn't duplicate the generic type parameters, I'll merge it and try to add in some improvements to get the string literals and custom attributes included etc.

Thanks!

**Comment by carterbush** [comment]
Makes sense to me, thanks for sanity checking that :)

**Comment by djkaty** [comment]
No problem, that's what code review is for :) Thanks for being patient!

**Comment by djkaty** [comment]
Obviously it would be great if I actually did the merge before closing the PR 😂

**Comment by djkaty** [comment]
The IDA code is now basically complete with lots of enhancements. Update your clone and give it a try :)

**Comment by carterbush** [comment]
Awesome! Can't wait to give it a go :)

**Comment by carterbush** [comment]
It's looking fantastic, @djkaty! Great job!

**Comment by djkaty** [comment]
Wow nice timing... I just pushed a 2.0 build finally now it's in the shape I want it to be! Hopefully people will start using it instead of *coughs* the, er... less comprehensive tool 😎

Really appreciate the continued words of encouragement :)

**Pull request merged**
